version: "3.8"

services:
  app:
    build: .
    container_name: EDITTHIS
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: always