[tool.poetry]
name = "sampletelegrambot"
version = "0.1"
description = ""
authors = ["Yooshyasha <mejzikrejzi66@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
tortoise-orm = {extras = ["asyncodbc"], version = "^0.21.5"}
aerich = "^0.7.2"
loguru = "^0.7.2"


[tool.poetry.dev-dependencies]
pytest = "^7.4.0"


[tool.poetry.scripts]
main = "sampletelegrambot.main:start"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
